# Generated by Django 4.2.5 on 2023-10-16 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garante',
            fields=[
                ('dni_garante', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TpoCliente',
            fields=[
                ('id_tpo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=255, null=True)),
                ('tel_cliente', models.CharField(max_length=15, null=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_cliente', models.TextField(blank=True, null=True)),
                ('dni_garante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.garante')),
                ('id_tpo_cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.tpocliente')),
            ],
        ),
    ]
