# Generated by Django 4.2.5 on 2023-11-03 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('ID_prop', models.AutoField(primary_key=True, serialize=False)),
                ('area_total', models.FloatField()),
                ('nro_habitaciones', models.IntegerField()),
                ('precio_alq', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cliente')),
            ],
        ),
    ]
