# Generated by Django 4.2.5 on 2023-11-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_propiedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/fotos/'),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/fotos/'),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/fotos/'),
        ),
    ]
