# Generated by Django 4.2.5 on 2023-09-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_id_cliente_id_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='garante_fecha_nacimiento',
            field=models.DateField(default='NULL'),
            preserve_default=False,
        ),
    ]
