# Generated by Django 4.2.5 on 2023-09-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='garante_fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default='exit'),
            preserve_default=False,
        ),
    ]
