# Generated by Django 4.2.5 on 2023-11-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('ID_convenio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.contrato')),
            ],
        ),
    ]
