# Generated by Django 4.2.5 on 2023-09-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion_garante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_inquilino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
