# Generated by Django 4.2.5 on 2023-09-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_cliente_direccion_garante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_garante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_inquilino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
